#
<<<<<<< HEAD
#Tue May 20 10:47:27 COT 2025
=======
#Tue May 20 17:30:31 COT 2025
>>>>>>> e42fffcef40b17bfb38fad1e65b9bb764e6ee29e
name=proyecto
browserName=chrome
unhandledPromptBehavior=ignore
version=
platform=ANY
